FROM golang:1.19-alpine as builder

ENV GO111MODULE on

WORKDIR /poly-go-server

# COPY go.mod, go.sum and download the dependencies
COPY go.* ./
RUN go mod download

# Copy the entire project and build it
COPY . /poly-go-server

RUN go build -ldflags -o server ./cmd/server

FROM alpine:latest
COPY --from=builder /poly-go-server /poly-go-server

EXPOSE 8080

ENTRYPOINT ["./poly-go-server/server"]
