version: '3.6'

volumes:
  postgres:
    driver: local

services:
  db: 
    image: postgres:9.6
    container_name: db
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: postgres -c max_connections=200 -c fsync=off -c synchronous_commit=off -c full_page_writes=off
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5555:5432
    restart: on-failure
    healthcheck:
      #CHANGE 1: this command checks if the database is ready, right on the source db server
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      default:
      go-graph:
        aliases: 
          - server
  
  server:
    container_name: go-graph-server
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /go/src/github.com/nitintf/graph-go
    entrypoint: make api-run
    env_file:
      - ./.env.local
    tty: true
    volumes:
      - .:/go/src/github.com/nitintf/graph-go
    ports:
      - "8080:8602"
    depends_on:
      - db
    networks:
      default:
      go-graph:
        aliases: 
          - server

networks:
  go-graph:
    name: go-graph-1
