FROM golang:1.19-alpine

ENV GO111MODULE on

RUN apk --update add openssh git alpine-sdk bash findutils

# Install tools required for project
# Run `docker build --no-cache .` to update dependencies
RUN go install -v -mod=mod github.com/codegangsta/gin@latest

WORKDIR /poly-go-server

# Copy the entire project and build it
COPY . /poly-go-server
